`timescale 1ns/1ps
module pipeline_tb;
    reg reset;
    reg clock;
    integer cycle_count;

    PipelineTop dut (
        .reset(reset),
        .clock(clock),
        .halted()
    );

`ifdef DUMP_VCD
    initial begin
        $dumpfile("pipeline.vcd");
        $dumpvars(0, pipeline_tb);
    end
`endif

    // -------------------------------------------------------------------------
    // Self-Checking Logic
    // -------------------------------------------------------------------------
    integer expected_file;
    integer scan_count;
    reg [31:0] exp_pc;
    reg [4:0]  exp_addr;
    reg [31:0] exp_data;
    reg synced;

    initial begin
        // Try to open the expected output file.
        // Using absolute path to ensure it finds the file generated by Mars
        expected_file = $fopen("D:\\PROGRAMMING\\ModernProcessorDeisgn\\Lab\\project_6-PipeLine\\expected.txt", "r");
        if (expected_file == 0) begin
            $display("WARNING: 'expected.txt' not found. Self-checking is DISABLED.");
        end else begin
            $display("INFO: 'expected.txt' found. Self-checking is ENABLED.");
            // Read the first line immediately to be ready for comparison
            scan_count = $fscanf(expected_file, "@%h: $%d <= %h\n", exp_pc, exp_addr, exp_data);
            synced = 0;
        end
    end

    always @(posedge clock) begin
        if (dut.register_file.reg_write && dut.register_file.write_addr != 0) begin
            if (expected_file != 0 && scan_count == 3) begin
                if (!synced) begin
                    // Synchronization phase: Look for the first matching write
                    if (exp_pc === dut.register_file.debug_pc && 
                        exp_addr === dut.register_file.write_addr && 
                        exp_data === dut.register_file.write_data) begin
                        
                        $display("INFO: Simulation synchronized with expected.txt at PC=%h", exp_pc);
                        synced = 1;
                        // Read next line
                        scan_count = $fscanf(expected_file, "@%h: $%d <= %h\n", exp_pc, exp_addr, exp_data);
                    end
                end else begin
                    // Synced phase: Strict checking
                    if (exp_pc !== dut.register_file.debug_pc || 
                        exp_addr !== dut.register_file.write_addr || 
                        exp_data !== dut.register_file.write_data) begin
                        
                        $display("\n[FAILED] Mismatch at time %t!", $time);
                        $display("  Expected: @%h: $%0d <= %h", exp_pc, exp_addr, exp_data);
                        $display("  Actual:   @%h: $%0d <= %h", dut.register_file.debug_pc, dut.register_file.write_addr, dut.register_file.write_data);
                        $stop;
                    end else begin
                        // Match found, read next line
                        scan_count = $fscanf(expected_file, "@%h: $%d <= %h\n", exp_pc, exp_addr, exp_data);
                    end
                end
            end
        end
    end

    integer k;
    initial begin
        reset = 1'b1;
        clock = 1'b0;
        cycle_count = 0;

        #5;
        clock = 1'b1; #5;
        clock = 1'b0; #5;
        reset = 1'b0;

        for (k = 0; k < 1000000; k = k + 1) begin
            clock = 1'b1; #5;
            clock = 1'b0; #5;
            cycle_count = cycle_count + 1;
            if (dut.halted) begin
                $display("Testbench detected halt at cycle %0d", cycle_count);
                if (expected_file != 0) begin
                    if ($fscanf(expected_file, "@%h: $%d <= %h\n", exp_pc, exp_addr, exp_data) == 3) begin
                        $display("\n[FAILED] Simulation halted, but expected file has more lines.");
                    end else begin
                        $display("\n[SUCCESS] Simulation passed! All writes match expected.txt.");
                    end
                end
                $finish;
            end
        end

        $display("Timeout: pipeline did not halt within max cycles.");
        $finish;
    end
endmodule
